### ISSUE TITLE
Resize to terminal dimension

### ISSUE THREAD

**Issue by stjohnfinn** [braheezy/violet#17]
I have my terminal full screen right now and its only taking up like a third of it. I believe this application should take advantage of as much real estate as it can. I guess really this issue could be reframed as "make it responsive". If there's no logic to resize larger, then I'm guessing there's no logic to make it resize smaller. Responsiveness would be good to add I think.

**Comment by braheezy** [comment]
I didn't see any built-in tools to BubbleTea or Bubbles to build a responsive UI. Which means you have to do the maths yourself by examining the current terminal size and choosing the layout accordingly.

I updated it so at least the content appears in the center of the terminal and moves as it's resized.

[Peek 2024-02-17 09-44.webm](https://github.com/braheezy/violet/assets/11700503/74b5f827-fe9a-4b81-858a-8b1935d768c9)
